version: "3.8"
services:
  db:
    image: postgres:15
    container_name: infradb_postgres
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-admin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-admin123}
      - POSTGRES_DB=${POSTGRES_DB:-appdb}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ../migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  backend:
    build: ../backend
    container_name: infradb_backend
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file:
      - ../.env

volumes:
  db_data:
